<?php

/**
 * This is the model base class for the table "artikel".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Artikel".
 *
 * Columns in table "artikel" available as properties of the model,
 * followed by relations of table "artikel" available as properties of the model.
 *
 * @property integer $id
 * @property integer $artikel_typ_id
 * @property string $name
 * @property string $bemerkung
 *
 * @property ArtikelTyp $artikelTyp
 * @property Verleih[] $verleihs
 */
abstract class BaseArtikel extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'artikel';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Artikel|Artikels', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('artikel_typ_id, name', 'required'),
			array('artikel_typ_id', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>128),
			array('bemerkung', 'safe'),
			array('bemerkung', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, artikel_typ_id, name, bemerkung', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'artikelTyp' => array(self::BELONGS_TO, 'ArtikelTyp', 'artikel_typ_id'),
			'verleihs' => array(self::HAS_MANY, 'Verleih', 'artikel_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'artikel_typ_id' => null,
			'name' => Yii::t('app', 'Name'),
			'bemerkung' => Yii::t('app', 'Bemerkung'),
			'artikelTyp' => null,
			'verleihs' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('artikel_typ_id', $this->artikel_typ_id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('bemerkung', $this->bemerkung, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}